# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FichesDePrep' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FichesDePrep
  pod 'RealmSwift'
  pod 'IQKeyboardManagerSwift'

  target 'FichesDePrepTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FichesDePrepUITests' do
    # Pods for testing
  end

end
